server:
  port: 8761
eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: false
security:
  user:
    password: wangqi
    name: root